
all: misc



misc:
# Avoiding all apps reopening when macOS crashes
	sudo chown root ~/Library/Preferences/ByHost/com.apple.loginwindow*
	sudo chmod 000 ~/Library/Preferences/ByHost/com.apple.loginwindow*
# To undo it, run:
# sudo rm -f ~/Library/Preferences/ByHost/com.apple.loginwindow*